version: 2

jobs:
  build:
    working_directory: ~/automatminer
    docker:
      - image: circleci/python:3.6.2
        environment:
          CODACY_PROJECT_TOKEN: "0cdf090f6d5f4f8783fcf3ce04c6a1d6"
          CI: "CIRCLE"
    steps:
      - checkout
      - run:
          name: setup env and run tests
          command: |
            python3 -m venv test_env
            . test_env/bin/activate
            pip install --upgrade pip
            pip install --quiet -r requirements.txt
            pip install --quiet -r requirements-optional.txt
            pip install coverage
            pip install codacy-coverage
            coverage run setup.py test
            coverage xml
            python-codacy-coverage -r coverage.xml
          no_output_timeout: 120m