version: 2

jobs:
  build:
    working_directory: ~/matbench
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          name: Make tox env
          command: |
            mkdir ~/tox_env
            python -m venv ~/tox_env
            source ~/tox_env/bin/activate
            pip install tox tox-pyenv
      - run:
          name: Run matbench tests
          command: |
            source ~/tox_env/bin/activate
            tox
          no_output_timeout: 15m
